export const data = {
  product: [
    {
      _id: "1",
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/1.jpeg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "ucuz urun",
    },
    {
      _id: "2",
      name: "Adidas Slim shirt",
      slug: "adidas-slim-shirt",
      category: "Shirts",
      image: "/images/2.jpeg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 5,
      numReviews: 10,
      description: "ucuz urun",
    },
    {
      _id: "3",
      name: "Nike Slim shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/3.jpeg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 1.5,
      numReviews: 10,
      description: "ucuz urun",
    },
    {
      _id: "4",
      name: "Nike Slim shirt",
      slug: "nike-slim-shirtt",
      category: "Shirts",
      image: "/images/4.jpeg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 2.5,
      numReviews: 10,
      description: "ucuz urun",
    },
    {
      _id: "5",
      name: "Nike Slim shirt",
      slug: "nike-slim-shirttt",
      category: "Shirts",
      image: "/images/5.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 3,
      numReviews: 10,
      description: "ucuz urun",
    },
  ],
};
