export const data = {
  product: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/1.jpeg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "ucuz urun",
    },
    {
      name: "Adidas Slim shirt",
      slug: "adidas-slim-shirt",
      category: "Shirts",
      image: "/images/2.jpeg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "ucuz urun",
    },
    {
      name: "Nike Slim shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/3.jpeg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "ucuz urun",
    },
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/4.jpeg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "ucuz urun",
    },
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/5.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "ucuz urun",
    },
  ],
};
